import type { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  // ───────── 下肢 ─────────
  {
    id: 'squat',
    name: '深蹲',
    category: 'lower',
    description: '雙腳與肩同寬，往下坐到大腿接近水平，再站起。',
    steps: ['雙腳與肩同寬，腳尖微微朝外', '背部打直，臀部往後坐', '膝蓋朝腳尖方向，蹲到大腿接近水平', '腳跟踩穩，站回起始位置'],
    metric: { kind: 'knee', side: 'both' },
    restValue: 168,
    targetValue: 100,
    mode: 'reps',
    minRepSeconds: 1.2,
    cues: { more: '再蹲低一點', reached: '很好，站起來', back: '好' },
    fullBody: true,
    defaultReps: 10,
  },
  {
    id: 'high_knee',
    name: '原地高抬腿',
    category: 'lower',
    description: '左右交替把膝蓋抬到腰的高度。',
    steps: ['站直，核心收緊', '一腳膝蓋抬到接近腰的高度', '放下後換另一腳', '保持節奏，上半身不要後仰'],
    metric: { kind: 'hip', side: 'alternate' },
    restValue: 172,
    targetValue: 100,
    mode: 'reps',
    minRepSeconds: 0.4,
    cues: { more: '膝蓋再抬高一點', reached: '好', back: '' },
    fullBody: true,
    defaultReps: 20,
  },
  {
    id: 'lunge',
    name: '弓箭步',
    category: 'lower',
    description: '一腳向前跨，前後膝各彎到約 90 度，再回到站姿。',
    steps: ['站直，一腳向前跨一大步', '身體垂直往下，前膝約 90 度', '後膝接近地面但不碰地', '前腳用力推回站姿，換腳'],
    metric: { kind: 'knee', side: 'alternate' },
    restValue: 170,
    targetValue: 105,
    mode: 'reps',
    minRepSeconds: 1.0,
    cues: { more: '再往下蹲一點', reached: '很好，推回來', back: '' },
    fullBody: true,
    defaultReps: 12,
  },
  {
    id: 'march',
    name: '原地踏步',
    category: 'lower',
    description: '輕鬆的原地踏步，做為熱身。',
    steps: ['站直，自然擺動手臂', '輪流抬腳，膝蓋抬到舒適高度', '保持呼吸順暢'],
    metric: { kind: 'hip', side: 'alternate' },
    restValue: 172,
    targetValue: 130,
    mode: 'reps',
    minRepSeconds: 0.3,
    cues: { more: '腳再抬高一點', reached: '', back: '' },
    fullBody: true,
    defaultReps: 30,
  },
  // ───────── 上肢 ─────────
  {
    id: 'lateral_raise',
    name: '手臂側平舉',
    category: 'upper',
    description: '雙手從身側往外抬到與肩同高，再慢慢放下。',
    steps: ['站直，雙手自然垂在身側', '手肘微彎，雙手往外側抬', '抬到與肩同高（手臂水平）', '慢慢放回身側'],
    metric: { kind: 'shoulder', side: 'both' },
    restValue: 20,
    targetValue: 85,
    mode: 'reps',
    minRepSeconds: 1.2,
    cues: { more: '手臂再抬高到肩膀高度', reached: '很好，慢慢放下', back: '' },
    fullBody: false,
    defaultReps: 12,
  },
  {
    id: 'overhead_raise',
    name: '雙手上舉',
    category: 'upper',
    description: '雙手從身側舉到頭頂上方伸直，再放下。',
    steps: ['站直，雙手垂在身側', '雙手往上舉，直到手臂在頭頂上方伸直', '肩膀不要聳起', '慢慢放下'],
    metric: { kind: 'armRaise', side: 'both' },
    restValue: 165,
    targetValue: 25,
    mode: 'reps',
    minRepSeconds: 1.2,
    cues: { more: '手再往上舉高一點', reached: '很好，放下', back: '' },
    fullBody: false,
    defaultReps: 12,
  },
  {
    id: 'bicep_curl',
    name: '手臂彎舉',
    category: 'upper',
    description: '手肘固定在身側，前臂彎起到肩膀附近再伸直。',
    steps: ['站直，手臂伸直，手掌朝前', '手肘固定在身側', '前臂往上彎到接近肩膀', '慢慢伸直回到起始'],
    metric: { kind: 'elbow', side: 'both' },
    restValue: 160,
    targetValue: 55,
    mode: 'reps',
    minRepSeconds: 1.0,
    cues: { more: '手再彎高一點', reached: '很好，慢慢伸直', back: '' },
    fullBody: false,
    defaultReps: 12,
  },
  // ───────── 關節活動度／復健 ─────────
  {
    id: 'shoulder_abduction_hold',
    name: '肩關節外展維持',
    category: 'mobility',
    description: '雙手往外側抬到與肩同高，維持 3 秒後放下。',
    steps: ['站直或坐直，雙手垂在身側', '雙手緩慢往外側抬高', '抬到與肩同高後停住 3 秒', '緩慢放下'],
    metric: { kind: 'shoulder', side: 'both' },
    restValue: 20,
    targetValue: 80,
    mode: 'hold',
    holdSeconds: 3,
    minRepSeconds: 2.0,
    cues: { more: '再抬高一點並停住', reached: '停住，維持', back: '' },
    fullBody: false,
    defaultReps: 6,
  },
  {
    id: 'knee_flexion',
    name: '膝關節屈伸',
    category: 'mobility',
    description: '坐在椅子上，一腳慢慢伸直再放下，訓練膝關節活動度。',
    steps: ['坐在椅子上，側面對相機', '一腳慢慢往前伸直', '伸直後慢慢彎回來', '兩腳輪流'],
    metric: { kind: 'knee', side: 'alternate' },
    restValue: 90,
    targetValue: 165,
    mode: 'reps',
    minRepSeconds: 1.5,
    cues: { more: '腳再伸直一點', reached: '很好，慢慢放下', back: '' },
    fullBody: true,
    defaultReps: 10,
  },
  {
    id: 'trunk_side_bend',
    name: '軀幹側彎',
    category: 'core',
    description: '面對相機站直，上半身緩慢往左右側彎。',
    steps: ['站直，雙腳與肩同寬', '一手沿大腿往下滑，上半身側彎', '停一下再回正', '換另一邊'],
    metric: { kind: 'trunkTilt', side: 'alternate' },
    restValue: 2,
    targetValue: 18,
    mode: 'reps',
    minRepSeconds: 1.0,
    cues: { more: '再往側邊彎一點', reached: '很好，回正', back: '' },
    fullBody: false,
    defaultReps: 10,
  },
  {
    id: 'arm_raise_hold',
    name: '雙手上舉維持',
    category: 'mobility',
    description: '雙手舉到頭頂上方，維持 3 秒後放下。',
    steps: ['站直或坐直', '雙手緩慢往上舉到頭頂上方', '停住 3 秒', '緩慢放下'],
    metric: { kind: 'armRaise', side: 'both' },
    restValue: 165,
    targetValue: 30,
    mode: 'hold',
    holdSeconds: 3,
    minRepSeconds: 2.0,
    cues: { more: '手再往上舉並停住', reached: '停住，維持', back: '' },
    fullBody: false,
    defaultReps: 5,
  },
];

export const EXERCISE_BY_ID: Record<string, Exercise> = Object.fromEntries(EXERCISES.map((e) => [e.id, e]));

export const CATEGORY_LABEL: Record<Exercise['category'], string> = {
  lower: '下肢',
  upper: '上肢',
  mobility: '關節活動度',
  core: '核心',
};
